[package]
name = "rusted-cargo"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5" # being used in separate files, not used at the moment
aggregator = {path = "../aggregator"}
uuid = {version = "1", features = ["v4"]}

[profile.release]
panic = 'abort'
